### ISSUE TITLE
osu_irc no longer working after server changes

### ISSUE THREAD

**Issue by TheMeq** [The-CJ/osu_irc.py#8]
Now getting this error after bot connects to irc. 

[MBOT]: Starting the bot...
[MBOT]: Connecting to MySQL...
[MBOT]: Connected to MySQL!
[MBOT]: Connecting to Bancho...
[MBOT]: Connected to Bancho!

Traceback (most recent call last):
  File "C:\venv\MeqBot\lib\site-packages\osu_irc\Classes\client.py", line 97, in main
    await self.listen()
  File "C:\venv\MeqBot\lib\site-packages\osu_irc\Classes\client.py", line 133, in listen
    if payload in ["", " ", None] or not payload: raise EmptyPayload()
osu_irc.Utils.errors.EmptyPayload
Task was destroyed but it is pending!
task: <Task pending coro=<addTraffic() running at C:\venv\MeqBot\lib\site-packages\osu_irc\Utils\traffic.py:13> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002AA753978B8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<addTraffic() running at C:\venv\MeqBot\lib\site-packages\osu_irc\Utils\traffic.py:13> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002AA753979D8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<addTraffic() running at C:\venv\MeqBot\lib\site-packages\osu_irc\Utils\traffic.py:13> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002AA75397858>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<trafficQuery() running at C:\venv\MeqBot\lib\site-packages\osu_irc\Utils\traffic.py:27> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002AA75397948>()]>>

**Comment by The-CJ** [comment]
soo it took some time, but now osu is next on my list, as i done with my twitch_irc lib, i will rewrite this one aswell,

i fixed that bug already and it will be applied in the next major version push.
are there any things you might want in the lib?

**Comment by The-CJ** [comment]
@TheMeq major update has been released, please test if anything workes.
if not let me know.

(gonna close this issue on 2020-09-30)
